<#
.SYNOPSIS
    Converts a BloodHound extension file into markdown (*.md) or MDX.
#>

#Requires -Version 5.1

[CmdletBinding()]
param (
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string] $ExtensionPath,

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $OutputPath = (Join-Path -Path $PSScriptRoot -ChildPath '../../Documentation/Schema.md'),

    [Parameter(Mandatory = $false)]
    [AllowNull()]
    [string] $NodeLinkBasePath = 'NodeDescriptions',

    [Parameter(Mandatory = $false)]
    [AllowNull()]
    [string] $EdgeLinkBasePath = 'EdgeDescriptions',

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $IconBasePath = 'Icons',

    [Parameter(Mandatory = $false)]
    [string] $GitHubBaseUrl = '',

    [Parameter(Mandatory = $false)]
    [switch] $OfficialDocs
)

Set-StrictMode -Version Latest

function Get-KindMarkdownLink {
    [CmdletBinding()]
    [OutputType([string])]
    param (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string] $KindName,

        [Parameter(Mandatory = $false)]
        [AllowNull()]
        [string] $LinkBasePath,

        [Parameter(Mandatory = $false)]
        [string] $Extension = '',

        [Parameter(Mandatory = $false)]
        [switch] $LowercasePath
    )

    [string] $pathName = if ($LowercasePath) { $KindName.ToLower() } else { $KindName }

    if ($null -eq $LinkBasePath) {
        return $KindName
    } elseif ([string]::Empty -eq $LinkBasePath) {
        return '[{0}]({1}{2})' -f $KindName, $pathName, $Extension
    } else {
        return '[{0}]({1}/{2}{3})' -f $KindName, $LinkBasePath, $pathName, $Extension
    }
}

# Parse the JSON file
[psobject] $json = Get-Content -Path $ExtensionPath | ConvertFrom-Json
[psobject[]] $nodeKinds = @($json.node_kinds | Sort-Object -Property name)
[psobject[]] $relationshipKinds = @($json.relationship_kinds | Sort-Object -Property name)
[string] $schemaName = $json.schema.name
[string] $schemaDisplayName = if (-not [string]::IsNullOrWhiteSpace($json.schema.display_name)) {
    $json.schema.display_name
} else {
    $schemaName
}
[string] $extensionFileName = Split-Path -Leaf $ExtensionPath

if ($OfficialDocs) {
    [string] $linkExtension = ''
    [string] $effectiveGitHubBaseUrl = if ([string]::IsNullOrEmpty($GitHubBaseUrl)) {
        'https://github.com/SpecterOps/{0}' -f $schemaName
    } else {
        $GitHubBaseUrl.TrimEnd('/')
    }
    # Compute repo-relative path for the GitHub link
    [string] $gitRoot = (& git -C (Split-Path -Parent $ExtensionPath) rev-parse --show-toplevel) -replace '\\', '/'
    [string] $extensionAbsolute = (Get-Item -Path $ExtensionPath).FullName -replace '\\', '/'
    [string] $extensionRepoRelPath = $extensionAbsolute.Substring($gitRoot.Length + 1)
    [string] $extensionFilePath = '{0}/blob/main/{1}' -f $effectiveGitHubBaseUrl, $extensionRepoRelPath
    [bool] $useMintlifyCallouts = $true
} else {
    [string] $linkExtension = '.md'
    # Compute relative path from the output directory to the extension file
    [string] $outputDir = (Get-Item -Path (Split-Path -Parent $OutputPath)).FullName
    [string] $resolvedExtensionPath = (Get-Item -Path $ExtensionPath).FullName
    Push-Location -Path $outputDir
    try {
        [string] $extensionFilePath = (Resolve-Path -Relative -Path $resolvedExtensionPath) -replace '\\', '/'
    } finally {
        Pop-Location
    }
    [bool] $useMintlifyCallouts = $false
}

# Generate the header and metadata section
[string] $markdown = ''
if ($OfficialDocs) {
    $markdown += @'
---
title: Schema
description: The OpenGraph extension schema for {0}
icon: circle-nodes
---

<img noZoom src="/assets/enterprise-AND-community-edition-pill-tag.svg" alt="Applies to BloodHound Enterprise and CE"/>

'@ -f $schemaName
}

if (-not $OfficialDocs) {
    $markdown += @'
# Schema

'@
}

$markdown += @'
## Metadata

**Name:** {0}<br />
**Display Name:** {1}<br />
**Version:** {2}<br />
**Namespace:** {3}<br />
**Environment Kind:** {4}<br />
**Source Kind:** {5}

'@ -f $schemaName, $schemaDisplayName, $json.schema.version, $json.schema.namespace, $json.environments[0].environment_kind, $json.environments[0].source_kind

$markdown += "`n"

if ($useMintlifyCallouts) {
    $markdown += @'
<Info>
This file is automatically generated from the [{0}]({1}) file
that is bundled with {2}.
</Info>
'@ -f $extensionFileName, $extensionFilePath, $schemaDisplayName
} else {
    $markdown += @'
> [!NOTE]
> This file is automatically generated from the [{0}]({1}) file
> that is bundled with {2}.
'@ -f $extensionFileName, $extensionFilePath, $schemaDisplayName
}

$markdown += "`n"
$markdown += @'

## Nodes

| Icon | Node Kind | Display Name |
|------|-----------|--------------|
'@

# Add a table row for each node kind
foreach ($nodeKind in $nodeKinds) {
    # Append node-specific markdown
    # Sample: | ![Okta_Organization](Icons/Okta_Organization.png) | Okta_Organization | Okta Organization |
    $markdown += "`n"
    [string] $nodeKindDisplay = Get-KindMarkdownLink -KindName $nodeKind.name -LinkBasePath $NodeLinkBasePath -Extension $linkExtension -LowercasePath:$OfficialDocs
    $markdown += '| ![{0}]({1}/{2}.png) | {3} | {4} |' -f $nodeKind.name, $IconBasePath, $nodeKind.name.ToLower(), $nodeKindDisplay, $nodeKind.display_name
}

$markdown += "`n`n"
$markdown += @'
## Edges

| Relationship Kind | Traversable | Description |
|-------------------|:-----------:|-------------|
'@

# Add a table row for each relationship kind
foreach ($relationshipKind in $relationshipKinds) {
    # Append relationship-specific markdown
    # Sample: | OktaUserHasRole | ✅ | Indicates that a user is assigned a role in Okta. |
    $markdown += "`n"
    [string] $traversableIcon = if ($relationshipKind.is_traversable) { '✅' } else { '❌' }
    [string] $relationshipKindDisplay = Get-KindMarkdownLink -KindName $relationshipKind.name -LinkBasePath $EdgeLinkBasePath -Extension $linkExtension -LowercasePath:$OfficialDocs
    $markdown += '| {0} | {1} | {2} |' -f $relationshipKindDisplay, $traversableIcon, $relationshipKind.description
}

# Normalize line endings to CRLF for Git working tree
$markdown = $markdown -replace "`r?`n", "`r`n"

# Create the Nodes.md file
Set-Content -Path $OutputPath -Value $markdown -Encoding UTF8 -Verbose
