<#
.SYNOPSIS
    Converts custom Cypher query files (*.json) into markdown (*.md) or MDX.
#>

#Requires -Version 5.1

[CmdletBinding()]
param (
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string] $ExtensionShortName,

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $InputDir = (Join-Path -Path $PSScriptRoot -ChildPath '../../../extension/saved_searches/'),

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $OutputPath = (Join-Path -Path $PSScriptRoot -ChildPath '../../queries.md'),

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string] $SavedSearchesLinkPath = '../extension/saved_searches',

    [Parameter(Mandatory = $false)]
    [string] $StripTitlePrefix = '',

    [Parameter(Mandatory = $false)]
    [switch] $OfficialDocs
)

Set-StrictMode -Version Latest

[string] $markdown = ''
if ($OfficialDocs) {
    $markdown += @'
---
title: Cypher Queries
description: {0} extension Cypher queries
icon: code
---

<img noZoom src="/assets/enterprise-AND-community-edition-pill-tag.svg" alt="Applies to BloodHound Enterprise and CE"/>

'@ -f $ExtensionShortName
} else {
    $markdown += @'
# Cypher Queries

'@
}

$markdown += @'
The following custom Cypher queries can be imported into BloodHound to enhance visibility.

'@

if ($OfficialDocs) {
    $markdown += @'
<Info>
This file is automatically generated from the [JSON query files]({0}).
</Info>

'@ -f $SavedSearchesLinkPath
} else {
    $markdown += @'
> [!NOTE]
> This file is automatically generated from the [JSON query files]({0}).

'@ -f $SavedSearchesLinkPath
}

Get-ChildItem -File -Path $InputDir -Filter '*.json' | Sort-Object -Property Name | ForEach-Object {
    # Parse the JSON content of the Cypher query file
    [psobject] $json = $null
    try {
        $json = Get-Content -Path $PSItem.FullName | ConvertFrom-Json
    }
    catch {
        Write-Error "Failed to parse query file '$($PSItem.FullName)': $($_.Exception.Message)"
        throw
    }

    if (-not $json.Name) {
        Write-Warning "Query file '$($PSItem.FullName)' is missing required 'Name' property. Skipping."
        return
    }
    if (-not $json.Query) {
        Write-Warning "Query file '$($PSItem.FullName)' is missing required 'Query' property. Skipping."
        return
    }

    # Remove optional title prefix for cleaner headings
    [string] $title = if ([string]::IsNullOrEmpty($StripTitlePrefix)) {
        $json.Name
    } else {
        $json.Name -replace [regex]::Escape($StripTitlePrefix)
    }

    # Sanitize line breaks in description and query
    [string] $description = $json.Description -replace '\n',"`n"
    [string] $query = $json.Query -replace '\n',"`n"

    [string] $fileName = $PSItem.Name

    # Append file-specific markdown
    $markdown += @'

## {0}

{1}

```cypher
{2}
```

This query can be imported into BloodHound from the [{3}]({4}/{3}) file.

'@ -f $title, $description, $query, $fileName, $SavedSearchesLinkPath
}

# Normalize line endings to CRLF for Git working tree
$markdown = $markdown -replace "`r?`n", "`r`n"

Set-Content -Path $OutputPath -Value $markdown -Encoding UTF8
Write-Host "Wrote $OutputPath" -ForegroundColor DarkGray
